实现 PyCore::eval 函数，支持直接运行Python代码
swoole/phpy pull request #10
Opened 2023-12-06 03:43 UTC by caiyili

## 主要功能

支持直接运行 python 代码，使用方式如下 ：

````php
<?php

$pycode = <<<CODE
import os

def printenv():
    for key, value in os.environ.items():
        print(f'{key}: {value}')

print("Hello!")
printenv()

CODE;

PyCore::eval($pycode);
````

## 应用场景

1. 低代码平台、或者在线代码运行平台

## 未解决问题：

1. 怎样给这段代码传递一个变量（类似 [Lua:assign](https://www.php.net/manual/en/class.lua.php)）
2. 怎样能让代码返回一个值到 php 中

2023-12-06 07:13 UTC, matyhtf commented
@caiyili 需要增加一个单测，tests/phpunit

2023-12-06 08:06 UTC, caiyili commented
> @caiyili 需要增加一个单测，tests/phpunit

@matyhtf  单元测试已经添加。 另外修改了代码，让外层 php 可以取到 python code 执行的结果，请 review

2023-12-06 09:40 UTC, matyhtf requested changes

2023-12-06 09:40 UTC, matyhtf commented on src/php/core.cc
> +        RETURN_FALSE;
这里可能会出现内存泄露，module 未销毁；如果 return false，globals 未销毁

2023-12-06 09:40 UTC, matyhtf commented on run-tests.php
修改这个文件的目的是？

2023-12-06 09:40 UTC, matyhtf commented on src/php/core.cc
> +    py2php(globals, return_value, true);
根据 Python 官方的文档，

```
[PyObject](https://docs.python.org/3/c-api/structures.html#c.PyObject) *PyRun_StringFlags(const char *str, int start, [PyObject](https://docs.python.org/3/c-api/structures.html#c.PyObject) *globals, [PyObject](https://docs.python.org/3/c-api/structures.html#c.PyObject) *locals, [PyCompilerFlags](https://docs.python.org/3/c-api/veryhigh.html#c.PyCompilerFlags) *flags)
Return value: New reference.
Execute Python source code from str in the context specified by the objects globals and locals with the compiler flags specified by flags. globals must be a dictionary; locals can be any object that implements the mapping protocol. The parameter start specifies the start token that should be used to parse the source code.

Returns the result of executing the code as a Python object, or NULL if an exception was raised.
```

返回值是执行代码的结果，这个是否可以利用呢？

2023-12-06 09:40 UTC, matyhtf commented on src/php/core.cc
> +    PyObject *module = PyImport_AddModule("__main__");
`__main__` 是否存在风险，如果多次执行 `eval` 是否会出现命名冲突

2023-12-06 09:57 UTC, matyhtf commented
这个写法，其实不是特别规范。 `globals, globals` ，实际上 python 里面是 `globals, locals` ，`locals` 未处理，`result` 直接丢弃了 。可以改成 `PyCore::eval($code, &$globals, &$locals)` ，传2个引用进去，让用户决定。而返回值，就应该是 Py 里的 `result`

2023-12-06 10:03 UTC, caiyili commented on src/php/core.cc
> +    py2php(globals, return_value, true);
最开始我是尝试直接返回 PyRun_StringFlags 执行的结果，但一直是空的。

根据 https://stackoverflow.com/questions/9573422/python-c-api-using-pyeval-evalcode 这里的描述

> If you want to evaluate an expression, you need to use Py_eval_input as an argument to Py_CompileString.
> My understanding of the matter is that:
> - Py_eval_input is equivalent to the built-in eval -- it evaluates an expression.
> - Py_file_input is equivalent to exec -- It executes Python code, but does not return anything.
> - Py_single_input evaluates an expression and prints its value -- used in the interpreter.

See [here](http://docs.python.org/c-api/veryhigh.html#Py_eval_input) for more, but the documentation on this subject is weak.

也就是只有用 `Py_eval_input` 这种方式，可以拿到结果。但这种方式只能写一个表达式，不能写复杂的语句。

因为执行一个 python 文件，确实是不能返回值的，不能在最外层写一个 return，所以这样也合理。

后来想到的办法是，拿到执行后的 globals 变量。但直接通过 PyEval_GetGlobals(); 获取全局变量，会报错段错误。

目前添加一个 `__main__` 模块，是参考的  [PyRun_SimpleStringFlags](https://hg.python.org/cpython/file/tip/Python/pythonrun.c#l414) 函数的实现。

2023-12-06 10:08 UTC, matyhtf commented on src/php/core.cc
> +    py2php(globals, return_value, true);
还有一个思路是，模块的名称可以随机，直接 `return module`，而通过读取 `module` 的 `globals` 和 `locals` 来获得执行过程中产生的全局变量和局部变量

2023-12-06 10:23 UTC, caiyili commented on run-tests.php
> 修改这个文件的目的是？

run-tests.php 是不是自动生成的，好像是编译过程中自己改了，以后我注意下提交的时候把这个排除掉。

2023-12-06 10:30 UTC, caiyili commented on src/php/core.cc
> +    PyObject *module = PyImport_AddModule("__main__");
试了一下，确实存在，运行2次就直接 `segmentation fault `

2023-12-07 04:43 UTC, caiyili commented
> 这个写法，其实不是特别规范。 `globals, globals` ，实际上 python 里面是 `globals, locals` ，`locals` 未处理，`result` 直接丢弃了 。可以改成 `PyCore::eval($code, &$globals, &$locals)` ，传 `2` 个引用进去，让用户决定如何使用。而返回值，就应该是 Py 里的 `result`


我研究了一下

1. 这里的 globals 传的是 PyModule_GetDict(module)，实际上就是取的 module 的一个指针 module->md_dict。只要把这个作为 globals 传给 PyRun_xx ，运行的结果才能通过 module 获取到。
2. 这个 locals 应该是作为一个函数内才有意义，作为一个模块外层代码是不是没有意义？我看 cpython 底层代码，如果locals为空，他会自动赋值成 globals。所以这里我就传NULL了 https://github.com/python/cpython/blob/16448cab44e23d350824e9ac75e699f5bcc48a14/Python/ceval.c#L566
3. 实际开发过程中，发现 globals 如果通过 Py_DECREF 翻译，程序运行完会出现 segmentation fault。我理解的是，因为他是 modules 的一个成员指针，并且存放了全局变量，这些变量后面要被php访问到，所以这里不能释放。不知道我理解的对不对。
4. 接受外部参数的功能，我目前还不会写。如果要实现的话，我考虑的方式是接收php的参数后，通过PyDict_SetItem(globals, key, value) 的形式，放到 globals 中去，让python代码可以读到。不知道这种方式是否可行。（或者是放到locals中，目前不太确定locals怎么用）

2023-12-07 06:03 UTC, matyhtf commented
@caiyili 好的，有一个冲突需要解决下，稍后合并

2023-12-07 06:52 UTC, caiyili commented
> @caiyili 好的，有一个冲突需要解决下，稍后合并

好的，冲突已解决

2023-12-07 07:05 UTC, merged

2023-12-07 10:06 UTC, he426100 commented
用内置函数就可以做到了
```
$py = PyCore::import('builtins')
$pycode = <<<CODE
import os

def printenv():
    for key, value in os.environ.items():
        print(f'{key}: {value}')


print("Hello!")
printenv()

CODE;
$py->eval($py->compile($pycode, '<string>', 'exec'), $py->dict())

$vars = $py->dict(['n' => 10])
$py->eval($py->compile('data = [ x**2 for x in range(n) if x % 2 ]', '<string>', 'exec'), $vars)
var_dump(PyCore::scalar($vars['data']));
```

![image](https://github.com/swoole/phpy/assets/9689137/2515ad6b-4f06-4460-814a-8c0ad7cd8925)

![45fa90e409f1b1008e11cf4df37b936](https://github.com/swoole/phpy/assets/9689137/f3195633-3eb0-4993-8cec-4aa4112df44a)